---
title: For The Love Of Nifty
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  snip-bits:
    title: Snip Bits
    output: true
  uploads:
    title: Uploads
    output: true
email: anubhavgupta2260@gmail.com
description: This blog is for those who won't work for money but their money will
  work for them Heading for a financially independent generation and a Money Smart
  India
baseurl: fortheloveofnifty
url: ''
twitter_username: 
instagram_username: anubhav.guptaa
theme: minima
plugins:
- jekyll-feed
